version: '3.6'
services:
  davinci:
    environment:
      - TIME_ZONE=Asia/Shanghai
      - SERVER_ADDRESS=0.0.0.0
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/davinci0.3?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=abc123123
      - SPRING_DATASOURCE_TEST_ON_BORROW=true
      - SPRING_DATASOURCE_TIME_BETWEEN_EVICTION_RUNS_MILLIS=6000
      - SPRING_MAIL_HOST=smtp.qq.com
      - SPRING_MAIL_PORT=465
      - SPRING_MAIL_USERNAME=2154747935@qq.com
      - SPRING_MAIL_PASSWORD=aA123456
      - SPRING_MAIL_NICKNAME=davinci
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_ENABLE=true
      - SCREENSHOT_DEFAULT_BROWSER=CHROME
      - SCREENSHOT_TIMEOUT_SECOND=15
      - SCREENSHOT_REMOTE_WEBDRIVER_URL=http://chrome:4444/wd/hub
    image: "edp963/davinci:v0.3.0-beta.9"
    ports:
      - 58080:8080
    command: ["./bin/docker-entrypoint.sh", "mysql:3306", "--", "start-server.sh"]
    restart: always
    volumes:
      - davinci_logs:/opt/davinci/logs
      - davinci_userfiles:/opt/davinci/userfiles
      - davinci_initdb:/initdb
    privileged: true
      # 如果要使用更多数据源，请将驱动挂载到/opt/davinci/lib/下面，类似下面
      # - kylin-jdbc-2.6.3.jar.jar:/opt/davinci/lib/kylin-jdbc-2.6.3.jar.jar
      # - mssql-jdbc-7.0.0.jre8.jar:/opt/davinci/lib/mssql-jdbc-7.0.0.jre8.jar
  chrome:
    image: selenium/standalone-chrome
    shm_size: 2g
  mysql:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=abc123123
      - MYSQL_DATABASE=davinci0.3
    volumes:
      - mysql_data:/var/lib/mysql
      - davinci_initdb:/docker-entrypoint-initdb.d:ro

volumes:
  davinci_userfiles:
  davinci_logs:
  davinci_initdb:
  mysql_data:

    
